server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/customer
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show_sql: 'true'
